"""Docker Compose integration for egg.

This module provides functionality for launching the egg stack (gateway +
orchestrator) using Docker Compose. The default ``egg`` CLI path uses
``ensure_compose_services()`` to start both services before launching the
sandbox container via ``docker run``.

Usage:
    egg                   # Default: compose up gateway+orchestrator, then sandbox
    egg --compose --down  # Stop the compose stack
    egg --compose --build # Rebuild images before starting
"""

import os
import subprocess
import time
from pathlib import Path

from .context import get_context
from .output import error, info, success, warn


def get_compose_file() -> Path:
    """Get path to the docker-compose.yml file.

    Searches for docker-compose.yml in:
    1. EGG_COMPOSE_FILE environment variable
    2. Current working directory
    3. Parent directories up to root
    4. Package installation directory

    Returns:
        Path to docker-compose.yml

    Raises:
        FileNotFoundError: If compose file cannot be found
    """
    # Check environment variable
    env_path = os.environ.get("EGG_COMPOSE_FILE")
    if env_path:
        compose_file = Path(env_path)
        if compose_file.exists():
            return compose_file
        raise FileNotFoundError(f"EGG_COMPOSE_FILE points to non-existent file: {env_path}")

    # Search current directory and parents
    current = Path.cwd()
    while current != current.parent:
        candidate = current / "docker-compose.yml"
        if candidate.exists():
            return candidate
        current = current.parent

    # Check package directory (for pip-installed egg)
    package_dir = Path(__file__).parent.parent.parent
    candidate = package_dir / "docker-compose.yml"
    if candidate.exists():
        return candidate

    raise FileNotFoundError(
        "docker-compose.yml not found. Either:\n"
        "  1. Run from the egg repository directory\n"
        "  2. Set EGG_COMPOSE_FILE environment variable\n"
        "  3. Run 'egg-deploy init' to set up configuration"
    )


def get_env_file(compose_file: Path) -> Path | None:
    """Get path to the .env file for compose.

    Args:
        compose_file: Path to docker-compose.yml

    Returns:
        Path to .env file if it exists, None otherwise
    """
    env_file = compose_file.parent / ".env"
    if env_file.exists():
        return env_file
    return None


def _generate_env_file(compose_file: Path) -> bool:
    """Generate .env file dynamically from the same sources as gateway docker run.

    Reads secrets, git identity, and host paths to produce a complete .env
    that docker-compose.yml can interpolate.

    Args:
        compose_file: Path to docker-compose.yml (env written next to it)

    Returns:
        True if .env was written successfully
    """
    from .gateway import _get_user_git_config, _load_secrets, get_launcher_secret

    ctx = get_context()
    config_dir = ctx.config_dir
    config_file = config_dir / "repositories.yaml"
    repos_dir = Path.home() / "repos"

    env_vars: dict[str, str] = {}

    # Host identity
    env_vars["HOST_UID"] = str(os.getuid())
    env_vars["HOST_GID"] = str(os.getgid())
    env_vars["HOST_HOME"] = str(Path.home())

    # Config and repos paths (host paths for volume mounts)
    env_vars["EGG_CONFIG_DIR"] = str(config_dir)
    env_vars["EGG_REPOS_DIR"] = str(repos_dir)

    # Launcher secret (read or generate)
    env_vars["EGG_LAUNCHER_SECRET"] = get_launcher_secret()

    # Secrets from ~/.config/egg/secrets.env
    secrets_dict = _load_secrets()
    if "GITHUB_USER_TOKEN" in secrets_dict:
        env_vars["GITHUB_USER_TOKEN"] = secrets_dict["GITHUB_USER_TOKEN"]
    if "BOT_GITHUB_TOKEN" in secrets_dict:
        env_vars["BOT_GITHUB_TOKEN"] = secrets_dict["BOT_GITHUB_TOKEN"]

    # Gateway policy configuration from secrets.env
    for key in ["GATEWAY_BOT_NAME", "GATEWAY_BOT_BRANCH_PREFIX", "GATEWAY_TRUSTED_USERS"]:
        if key in secrets_dict:
            env_vars[key] = secrets_dict[key]

    # Git identity from repositories.yaml
    if config_file.exists():
        git_name, git_email = _get_user_git_config(config_file)
        if git_name:
            env_vars["EGG_USER_GIT_NAME"] = git_name
        if git_email:
            env_vars["EGG_USER_GIT_EMAIL"] = git_email

    # Write .env file
    env_file = compose_file.parent / ".env"
    lines = [
        "# Auto-generated by egg — do not edit manually",
        "# Regenerated on each egg invocation",
        "",
    ]
    for key, value in sorted(env_vars.items()):
        # Quote values that contain spaces or special chars
        if " " in value or "#" in value or "'" in value:
            lines.append(f'{key}="{value}"')
        else:
            lines.append(f"{key}={value}")

    env_file.write_text("\n".join(lines) + "\n")
    return True


def _has_docker_compose() -> bool:
    """Check if docker compose (v2 plugin) is available."""
    try:
        result = subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True,
            timeout=10,
            check=False,
        )
        return result.returncode == 0
    except Exception:
        return False


def compose_up(compose_file: Path, build: bool = False) -> bool:
    """Start the egg stack using Docker Compose.

    Args:
        compose_file: Path to docker-compose.yml
        build: Whether to rebuild images

    Returns:
        True if successful, False otherwise
    """
    info("Starting egg services via Docker Compose...")

    cmd = [
        "docker",
        "compose",
        "-f",
        str(compose_file),
        "up",
        "-d",
    ]

    if build:
        cmd.append("--build")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=False)
        if result.returncode != 0:
            error(f"Docker Compose failed: {result.stderr}")
            return False
        return True
    except FileNotFoundError:
        error("Docker Compose not found. Please install Docker Compose.")
        return False
    except Exception as e:
        error(f"Failed to run Docker Compose: {e}")
        return False


def compose_down(compose_file: Path) -> bool:
    """Stop and remove the egg stack.

    Args:
        compose_file: Path to docker-compose.yml

    Returns:
        True if successful, False otherwise
    """
    info("Stopping egg stack via Docker Compose...")

    cmd = [
        "docker",
        "compose",
        "-f",
        str(compose_file),
        "down",
        "--remove-orphans",
    ]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=False)
        if result.returncode != 0:
            error(f"Docker Compose down failed: {result.stderr}")
            return False
        success("Egg stack stopped")
        return True
    except Exception as e:
        error(f"Failed to stop stack: {e}")
        return False


def _wait_for_health(url: str, label: str, timeout: int = 60) -> bool:
    """Wait for a service health endpoint to respond.

    Args:
        url: Health check URL
        label: Service label for log messages
        timeout: Maximum seconds to wait

    Returns:
        True if healthy, False on timeout
    """
    import urllib.error
    import urllib.request

    start = time.time()
    while time.time() - start < timeout:
        try:
            with urllib.request.urlopen(url, timeout=3) as resp:
                if resp.status == 200:
                    return True
        except (urllib.error.URLError, OSError):
            pass
        time.sleep(1)

    error(f"{label} health check timed out after {timeout}s")
    return False


def ensure_compose_services(build: bool = False) -> bool:
    """Start gateway + orchestrator via Docker Compose.

    This is the primary entry point used by the default ``egg`` CLI path.
    It:
    1. Locates docker-compose.yml
    2. Generates .env dynamically from the same config sources as
       ``start_gateway_container()`` (secrets.env, repositories.yaml, etc.)
    3. Runs ``docker compose up -d``
    4. Waits for gateway health check
    5. Waits for orchestrator health check (non-blocking on failure)

    Falls back to ``start_gateway_container()`` if docker compose is
    unavailable.

    Args:
        build: Force rebuild of compose images

    Returns:
        True if gateway is healthy (orchestrator failure is a warning only)
    """
    # Check docker compose availability
    if not _has_docker_compose():
        warn("Docker Compose not available, falling back to docker run")
        from .gateway import start_gateway_container

        return start_gateway_container()

    # Find compose file
    try:
        compose_file = get_compose_file()
    except FileNotFoundError:
        warn("docker-compose.yml not found, falling back to docker run")
        from .gateway import start_gateway_container

        return start_gateway_container()

    # Generate .env from current config
    if not _generate_env_file(compose_file):
        error("Failed to generate .env for Docker Compose")
        return False

    # Start services
    if not compose_up(compose_file, build=build):
        return False

    ctx = get_context()

    # Wait for gateway health
    gateway_url = f"http://localhost:{ctx.gateway_port}/api/v1/health"
    info("Waiting for gateway health check...")
    if not _wait_for_health(gateway_url, "Gateway", timeout=60):
        error("Gateway failed to start. Check logs: docker compose logs gateway")
        return False
    success("Gateway is healthy")

    # Wait for orchestrator health (non-blocking — orchestrator is optional)
    orchestrator_url = f"http://localhost:{ctx.orchestrator_port}/api/v1/health"
    info("Waiting for orchestrator health check...")
    if _wait_for_health(orchestrator_url, "Orchestrator", timeout=30):
        success("Orchestrator is healthy")
    else:
        warn("Orchestrator not healthy — continuing without it")

    return True


def stop_compose_services() -> bool:
    """Stop the compose stack (gateway + orchestrator).

    Returns:
        True if stopped successfully
    """
    try:
        compose_file = get_compose_file()
    except FileNotFoundError:
        warn("docker-compose.yml not found, nothing to stop")
        return True

    return compose_down(compose_file)


def get_compose_gateway_ip(compose_file: Path) -> str:
    """Get the gateway container IP from compose stack.

    Args:
        compose_file: Path to docker-compose.yml

    Returns:
        Gateway IP address (default 172.32.0.2)
    """
    # The compose file uses fixed IPs - read project name to construct container name
    project_name = "egg"
    env_file = get_env_file(compose_file)
    if env_file:
        with open(env_file) as f:
            for line in f:
                if line.startswith("COMPOSE_PROJECT_NAME="):
                    project_name = line.split("=", 1)[1].strip()
                    break

    container_name = f"{project_name}-gateway"

    try:
        result = subprocess.run(
            [
                "docker",
                "inspect",
                container_name,
                "--format",
                '{{with index .NetworkSettings.Networks "'
                + project_name
                + '-isolated"}}{{.IPAddress}}{{end}}',
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        ip = result.stdout.strip()
        if ip:
            return ip
    except Exception:
        pass

    # Fall back to default
    return "172.32.0.2"


def run_compose_mode(down: bool = False, build: bool = False) -> int:
    """Run egg in explicit compose control mode.

    Used by ``egg --compose --down`` and ``egg --compose --build``.

    Args:
        down: If True, stop the stack and exit
        build: If True, rebuild images before starting

    Returns:
        Exit code (0 for success)
    """
    try:
        compose_file = get_compose_file()
    except FileNotFoundError as e:
        error(str(e))
        return 1

    info(f"Using compose file: {compose_file}")

    # Handle --compose --down
    if down:
        if compose_down(compose_file):
            return 0
        return 1

    # Generate .env and start
    if not _generate_env_file(compose_file):
        return 1

    if not compose_up(compose_file, build=build):
        return 1

    ctx = get_context()

    # Wait for gateway health
    gateway_url = f"http://localhost:{ctx.gateway_port}/api/v1/health"
    info("Waiting for gateway health check...")
    if not _wait_for_health(gateway_url, "Gateway", timeout=60):
        error("Gateway failed to start. Check logs: docker compose logs gateway")
        return 1

    success("Gateway is healthy")

    # Wait for orchestrator health
    orchestrator_url = f"http://localhost:{ctx.orchestrator_port}/api/v1/health"
    info("Waiting for orchestrator health check...")
    if _wait_for_health(orchestrator_url, "Orchestrator", timeout=30):
        success("Orchestrator is healthy")
    else:
        warn("Orchestrator not healthy — continuing without it")

    return 0
