"""Context management and compaction for the egg harness."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger(__name__)

# Compaction summary is generated by asking the model to summarize
COMPACTION_PROMPT = """Summarize the conversation so far concisely. Include:
1. The original task/goal
2. Key decisions made
3. Current progress and state
4. Files modified or created
5. Any errors encountered and how they were resolved
6. What needs to be done next

Be specific — include file paths, function names, and concrete details.
This summary will replace the conversation history, so nothing important should be lost."""


@dataclass
class CompactionState:
    """Tracks compaction state to prevent infinite loops."""

    compaction_count: int = 0
    recent_compaction_turns: list[int] = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.recent_compaction_turns is None:
            self.recent_compaction_turns = []

    def should_compact(
        self,
        current_tokens: int,
        max_tokens: int,
        threshold: float,
        current_turn: int,
        max_compactions_per_window: int = 2,
        window_turns: int = 5,
    ) -> bool:
        """Determine if compaction should be triggered."""
        if current_tokens < max_tokens * threshold:
            return False

        # Check for compaction loop: too many compactions in recent turns
        recent = [t for t in self.recent_compaction_turns if current_turn - t <= window_turns]
        if len(recent) >= max_compactions_per_window:
            logger.error(
                f"Compaction loop detected: {len(recent)} compactions in last {window_turns} turns. "
                f"Aborting to prevent infinite loop."
            )
            return False  # Caller should handle this as a fatal error

        return True

    def is_loop_detected(
        self,
        current_turn: int,
        max_compactions_per_window: int = 2,
        window_turns: int = 5,
    ) -> bool:
        """Check if we're in a compaction loop (should abort)."""
        recent = [t for t in self.recent_compaction_turns if current_turn - t <= window_turns]
        return len(recent) >= max_compactions_per_window

    def record_compaction(self, turn: int) -> None:
        """Record that compaction happened at this turn."""
        self.compaction_count += 1
        self.recent_compaction_turns.append(turn)


def build_compaction_messages(
    summary: str,
    system_prompt: str | None = None,
) -> list[dict[str, Any]]:
    """Build the message list for post-compaction state.

    After compaction, the conversation is reset to:
    1. A user message containing the summary
    2. An assistant acknowledgment
    """
    messages: list[dict[str, Any]] = [
        {
            "role": "user",
            "content": (
                "The conversation history has been compacted. Here is the summary of "
                "everything that happened so far:\n\n"
                f"{summary}\n\n"
                "Continue from where we left off. Do not repeat completed work."
            ),
        },
        {
            "role": "assistant",
            "content": (
                "Understood. I have the full context from the summary. "
                "Continuing from where we left off."
            ),
        },
    ]
    return messages


def estimate_message_tokens(messages: list[dict[str, Any]]) -> int:
    """Rough token estimate for messages (4 chars ≈ 1 token)."""
    total_chars = 0
    for msg in messages:
        content = msg.get("content", "")
        if isinstance(content, str):
            total_chars += len(content)
        elif isinstance(content, list):
            for block in content:
                if isinstance(block, dict):
                    if "text" in block:
                        total_chars += len(block["text"])
                    elif "content" in block:
                        c = block["content"]
                        total_chars += len(c) if isinstance(c, str) else len(str(c))

    return total_chars // 4  # Rough approximation
