"""Integration tests for gateway policies around babysit-pr staging branches.

The gateway restricts which branches an agent is allowed to push. In the
post-#1748 babysit-pr flow, each producer pushes to a staging branch of
the form ``egg/babysit-pr/{pr}/{short-sha}/{role}``.

The allowed branch pattern (``egg/`` prefix) is enforced by the gateway's
policy in ``gateway/``; these tests document the staging-branch naming
contract that the orchestrator side of the flow generates, so the
gateway-side pattern continues to accept them.
"""

from __future__ import annotations

import pytest


@pytest.mark.integration
class TestStagingBranchNaming:
    """Staging branches generated by the orchestrator are ``egg/``-prefixed."""

    def test_staging_branch_has_egg_prefix(self):
        """The staging branch pattern starts with ``egg/`` so the gateway allows pushes.

        This is a contract test — if the staging-branch prefix ever changes
        away from ``egg/`` the gateway rule would need to change too.
        """
        from concurrent_executor import AgentRole, ConcurrentPhaseExecutor
        from models import Pipeline, PipelineMode

        pipeline = Pipeline(
            id="pr-42",
            repo="owner/repo",
            mode=PipelineMode.BABYSIT,
            pr_number=42,
            pr_head_sha="abc1234deadbeef5678901234567890abcdefabc",
            branch="feature-x",
            has_contract=False,
        )
        executor = ConcurrentPhaseExecutor.__new__(ConcurrentPhaseExecutor)  # type: ignore[call-arg]
        executor.pipeline = pipeline
        executor._roles_override = None

        for role in (AgentRole.CODER, AgentRole.TESTER, AgentRole.DOCUMENTER):
            branch = executor.get_worktree_branch(role)
            assert branch.startswith("egg/"), (
                f"Staging branch {branch!r} for {role} must start with 'egg/' "
                "so the gateway allows pushes."
            )

    def test_staging_branch_includes_role(self):
        """Each producer's staging branch includes its role name."""
        from concurrent_executor import AgentRole, ConcurrentPhaseExecutor
        from models import Pipeline, PipelineMode

        pipeline = Pipeline(
            id="pr-42",
            repo="owner/repo",
            mode=PipelineMode.BABYSIT,
            pr_number=42,
            pr_head_sha="abc1234deadbeef5678901234567890abcdefabc",
            branch="feature-x",
            has_contract=False,
        )
        executor = ConcurrentPhaseExecutor.__new__(ConcurrentPhaseExecutor)  # type: ignore[call-arg]
        executor.pipeline = pipeline
        executor._roles_override = None

        assert executor.get_worktree_branch(AgentRole.CODER).endswith("/coder")
        assert executor.get_worktree_branch(AgentRole.TESTER).endswith("/tester")
        assert executor.get_worktree_branch(AgentRole.DOCUMENTER).endswith("/documenter")

    def test_staging_branch_namespaced_by_pr_and_sha(self):
        """Different PR head SHAs produce distinct staging branches.

        This prevents collisions when the same PR is babysat twice after a
        human pushes a new commit.
        """
        from concurrent_executor import AgentRole, ConcurrentPhaseExecutor
        from models import Pipeline, PipelineMode

        executor = ConcurrentPhaseExecutor.__new__(ConcurrentPhaseExecutor)  # type: ignore[call-arg]
        executor._roles_override = None

        pipeline_v1 = Pipeline(
            id="pr-42",
            repo="owner/repo",
            mode=PipelineMode.BABYSIT,
            pr_number=42,
            pr_head_sha="abc1234deadbeef",
            branch="feature-x",
            has_contract=False,
        )
        pipeline_v2 = Pipeline(
            id="pr-42",
            repo="owner/repo",
            mode=PipelineMode.BABYSIT,
            pr_number=42,
            pr_head_sha="def5678cafebabe",
            branch="feature-x",
            has_contract=False,
        )

        executor.pipeline = pipeline_v1
        branch_v1 = executor.get_worktree_branch(AgentRole.CODER)
        executor.pipeline = pipeline_v2
        branch_v2 = executor.get_worktree_branch(AgentRole.CODER)

        assert branch_v1 != branch_v2
        assert "abc1234" in branch_v1
        assert "def5678" in branch_v2
