"""Re-export anchor constants from egg_config for convenience."""

try:
    from egg_config.constants import (
        ANCHOR_HARD_LIMIT_BYTES,
        ANCHOR_MAX_DECISIONS,
        ANCHOR_MAX_ERRORS,
        ANCHOR_MAX_FILES,
        ANCHOR_MAX_KEY_CONTEXT,
        ANCHOR_MAX_PROGRESS_ITEMS,
        ANCHOR_REDIS_PREFIX,
        ANCHOR_SOFT_LIMIT_BYTES,
        ANCHOR_TEAM_HARD_LIMIT_BYTES,
        ANCHOR_TEAM_SOFT_LIMIT_BYTES,
    )
except ImportError:
    # Fallback values when egg_config is not available
    ANCHOR_SOFT_LIMIT_BYTES = 2048
    ANCHOR_HARD_LIMIT_BYTES = 3072
    ANCHOR_TEAM_SOFT_LIMIT_BYTES = 4096
    ANCHOR_TEAM_HARD_LIMIT_BYTES = 6144
    ANCHOR_REDIS_PREFIX = "anchor"
    ANCHOR_MAX_PROGRESS_ITEMS = 10
    ANCHOR_MAX_DECISIONS = 8
    ANCHOR_MAX_KEY_CONTEXT = 5
    ANCHOR_MAX_ERRORS = 5
    ANCHOR_MAX_FILES = 15

__all__ = [
    "ANCHOR_HARD_LIMIT_BYTES",
    "ANCHOR_MAX_DECISIONS",
    "ANCHOR_MAX_ERRORS",
    "ANCHOR_MAX_FILES",
    "ANCHOR_MAX_KEY_CONTEXT",
    "ANCHOR_MAX_PROGRESS_ITEMS",
    "ANCHOR_REDIS_PREFIX",
    "ANCHOR_SOFT_LIMIT_BYTES",
    "ANCHOR_TEAM_HARD_LIMIT_BYTES",
    "ANCHOR_TEAM_SOFT_LIMIT_BYTES",
]
