apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: egg-system
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: egg
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: gateway
  ports:
    - name: api
      port: 9848
      targetPort: 9848
      protocol: TCP
    - name: proxy
      port: 3129
      targetPort: 3129
      protocol: TCP
    - name: health
      port: 9851
      targetPort: 9851
      protocol: TCP
