apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: egg-system
  labels:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/part-of: egg
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orchestrator
  ports:
    - name: api
      port: 9849
      targetPort: 9849
      protocol: TCP
